accounts/urls.py
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.myAccount),
    path('registerUser/',views.registerUser, name='registerUser'),
    path('registerVendor/',views.registerVendor, name='registerVendor'),
    
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),

    path('activate/<uidb64>/<token>/',views.activate, name='activate'),

    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/',views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/',views.reset_password, name='reset_password'),

    path('myAccount/',views.myAccount, name='myAccount'),
    path('userHome/',views.userHome, name='userHome'),
    path('vendorHome/',views.vendorHome, name='vendorHome'),

    path('vendor_dashboard/',views.vendor_dashboard, name='vendor_dashboard'),
    path('v_orders/',views.v_orders, name='v_orders'),
    path('v_orders_detail/<int:order_id>',views.v_orders_detail, name='v_orders_detail'),

    path('user_dashboard/',views.user_dashboard, name='user_dashboard'),
    path('my_orders/',views.my_orders, name='u_my_orders'),
    path('my_orders_detail/<int:order_id>',views.my_orders_detail, name='u_my_orders_detail'),

    path('on_road/',views.on_road, name='on_road'),

    path('search/',views.search, name='search'),

    path('service/<int:vendor_id>/',views.service, name='service'),
    
    path('order/<int:vendor_id>/',views.order, name='order'),
    path('home_service/<int:vendor_id>/',views.home_service, name='home_service'),
    
    path('ajax/load-models/',views.load_models, name='ajax_load_models'),

    path('order_detail/<int:order_id>/',views.order_detail, name='order_detail'),
    path('order_bill/<int:order_id>/',views.order_bill, name='order_bill'),
    path('order_bill/',views.order_bill, name='order_bill'),

    path('user_bill/',views.user_bill, name='user_bill'),

    path('accept/<int:order_id>/',views.accept, name='accept'),
    path('decline/<int:order_id>/',views.decline, name='decline'),

    path('end_page/<uidb64>/<order_id>/',views.end_page, name='end_page'),


    path('vendor/',include('vendor.urls')),


   

    path('u_profile/',views.u_profile, name='u_profile'),

    path('admin_login/',views.admin_login, name='admin_login'),
    path('admin_logout/',views.admin_logout, name='admin_logout'),
    path('admin_home/',views.admin_dashboard, name='admin_dashboard'),
    path('admin_orders/',views.admin_orders, name='admin_orders'),
    path('admin_orders_detail/<int:order_id>',views.admin_orders_detail, name='admin_orders_detail'),

    path('admin_vendors/',views.admin_vendors, name='admin_vendors'),
    path('admin_users/',views.admin_users, name='admin_users'),

    path('admin_bill/',views.admin_bill, name='admin_bill'),
    path('user_block/<int:id>/',views.user_block, name='user_block'),
    path('user_unblock/<int:id>/',views.user_unblock, name='user_unblock'),
    path('vendor_block/<int:id>/',views.vendor_block, name='vendor_block'),
    path('vendor_unblock/<int:id>/',views.vendor_unblock, name='vendor_unblock'),


]

ajio_main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from accounts.models import User
from vendor.models import Vendor
from django.db.models import Count
# Create your models here.
class Defects(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
        
class Vehicle(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Models(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name 

 

class Types(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Orders(models.Model):
    TYPE = [
        ('ROAD', 'ROAD'),
        ('HOME', 'HOME'),
    ]
    STATUS_CHOICES = [
        ('NEW', 'NEW'),
        ('ACCEPTED', 'ACCEPTED'),
        ('DECLINED', 'DECLINED'),
        ('COMPLETED', 'COMPLETED'),
        ('PENDING', 'PENDING'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, blank=True, null=True)
    service = models.CharField(max_length=10, choices=TYPE, blank=True)
    u_phone_number = models.CharField(max_length=12, blank=True)
    v_phone_number = models.CharField(max_length=12, blank=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='NEW')
    type = models.ForeignKey(Types, on_delete=models.CASCADE, blank=True, null=True)
    model = models.ForeignKey(Models, on_delete=models.CASCADE, blank=True, null=True)
    defect = models.ForeignKey(Defects, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50, blank=True, null=True)
    eta = models.CharField(max_length=200, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    msg = models.TextField(blank=True, null=True)
    is_seen = models.BooleanField(default=False)
    date = models.DateField(blank=True,null=True)
    time = models.TimeField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.description

  

class Order_images(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='product_images')

    def __str__(self):
        return self.order.description       
   
                       

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import UserForm,OrderForm,UserProfileForm, UserInfoForm
from vendor.forms import VendorForm
from .models import User,UserProfile
from django.contrib import messages,auth
from .utils import detect_user,send_verification_email,send_service_email
from django.contrib.auth.decorators import login_required,user_passes_test
from django.core.exceptions import PermissionDenied
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from vendor.models import Vendor
from django.contrib.gis.geos import GEOSGeometry
from django.views.decorators.cache import cache_control
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance
from orders.models import Orders,Order_images,Models
from django.db.models import Q
from django.db.models import Count
from django.utils import timezone
from django.db.models.functions import ExtractMonth
import calendar
import datetime

# Create your views here.

# Restrict vendor from user's pages
def check_role_vendor(user):
    if user.role == 1:
        return True
    else:
        raise PermissionDenied    

# Restrict user from vendor's pages
def check_role_user(user):
    if user.role == 2:
        return True
    else:
        raise PermissionDenied    

def registerUser(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            user = form.save(commit=False)
            user.set_password(password)
            user.role = User.CUSTOMER
            user.save()

            # send verification email
            mail_subject = 'Please activate your Account'
            email_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request,user, mail_subject, email_template) 

            messages.success(request, 'Registration Sucessful')
            messages.success(request, 'Check your E-mail')
            return redirect('registerUser')
        else:
            print('invalid form')
            print(form.errors)    
    else:
        form = UserForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/registerUser.html', context)

def registerVendor(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        v_form = VendorForm(request.POST, request.FILES)
        if form.is_valid() and v_form.is_valid:
            password = form.cleaned_data['password']
            user = form.save(commit=False)
            user.set_password(password)
            user.role = User.VENDOR
            print(user.role)
            user.save()
            vendor = v_form.save(commit=False)
            vendor.user = user
            user_profile = UserProfile.objects.get(user=user)
            vendor.user_profile = user_profile
            vendor.save()

            # send verification email
            mail_subject = 'Please activate your Account'
            email_template = 'accounts/emails/account_verification_email.html'
            send_verification_email(request,user, mail_subject, email_template) 

            messages.success(request, 'Registration Sucessful. Check your E-mail')
            return redirect('registerVendor')
        else:
            print('Invalid form')
            print(form.errors)
    else:
        form = UserForm()
        v_form = VendorForm()

    context = {
        'form': form,
        'v_form': v_form
    }
    return render(request, 'accounts/registerVendor.html', context)

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congrajulation ! Your account activated.')  
        return redirect('myAccount')
    else:
        messages.error(request, 'Invalid activation link.')         
        return redirect('myAccount')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login(request):
    if request.user.is_authenticated:
        messages.warning(request,'You already logged in !')
        return redirect('myAccount')    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are logged in')
            return redirect('myAccount')  
        else:
            messages.error(request, 'Invalid Credentials')
            return redirect('login')    
    return render(request, 'accounts/login.html') 


def logout(request):
    auth.logout(request)
    messages.info(request,'You are logged out')
    return redirect('login')

@login_required(login_url ='login')
def myAccount(request):
    user = request.user
    redirectUrl = detect_user(user)
    return redirect(redirectUrl)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url ='login')
@user_passes_test(check_role_user)
def userHome(request):
    if request.user.is_active and request.user.is_blocked:
        user = request.user
        orders = Orders.objects.filter(user=user,is_seen=False)
        vendors = Vendor.objects.all()[:8]
        return render(request,'home.html',{'orders':orders,'vendors':vendors})
    else:
        messages.error(request, 'You are restricted from this Site') 
        return redirect('login')   


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url ='login')
@user_passes_test(check_role_vendor)
def vendorHome(request):
    vendor_id = request.user.id
    vendor = Vendor.objects.get(user__id=vendor_id)
    orders = Orders.objects.filter(vendor=vendor,status='NEW').order_by('-created_at')
    return render(request,'v_home.html',{'orders':orders})

@login_required(login_url ='login')
@user_passes_test(check_role_vendor)
def vendor_dashboard(request):
    vendor = Vendor.objects.get(user=request.user)
    orders = Orders.objects.filter(vendor=vendor).order_by('-created_at')
    recent_orders = orders[:5]
    
    current_month = datetime.datetime.now().month
    current_month_orders = orders.filter(created_at__month=current_month)
    current_month_revenue = 0
    for i in current_month_orders:
        if i.price:
            current_month_revenue += int(i.price)    

    total_revenue = 0
    for i in orders:
        if i.price:
           total_revenue += int(i.price)

    context = {
        'recent_orders':recent_orders,
        'orders_count':orders.count(),
        'total_revenue':total_revenue,
        'current_month_revenue':current_month_revenue,
    }    

    return render(request,'accounts/vendor_dashboard.html', context)   

@login_required(login_url ='login')
def user_dashboard(request):
    orders = Orders.objects.filter(user=request.user).order_by('-created_at')
    recent_orders = orders[:5]
    context = {'orders':orders,
               'recent_orders':recent_orders,
               'orders_count':orders.count(),
              }
    return render(request,'accounts/user_dashboard.html',context)      

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def my_orders(request):
    orders = Orders.objects.filter(user=request.user).order_by('-created_at')
    context = {'orders':orders}
    return render(request, 'user/my_orders.html', context)     

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def v_orders(request):
    vendor = Vendor.objects.get(user=request.user)
    orders = Orders.objects.filter(vendor=vendor).order_by('-created_at')
    context = {'orders':orders}
    print(orders)
    return render(request, 'vendor/my_orders.html', context)      


def my_orders_detail(request, order_id):
    order = Orders.objects.get(id=order_id)
    return render(request, 'user/my_orders_detail.html',{'order':order})   

def v_orders_detail(request, order_id):
    order = Orders.objects.get(id=order_id)
    return render(request, 'vendor/my_orders_detail.html',{'order':order})    

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)
            
            mail_subject = 'Reset Your Password'
            email_template = 'accounts/emails/reset_password_email.html'
            send_verification_email(request, user, mail_subject, email_template)
            messages.success(request, 'Password reset link has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account does not exist.')
            return redirect('forgot_password')   

    return render(request, 'accounts/forgot_password.html')   

def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user,token):
        request.session['uid'] = uid   

orders/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/home_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}"></script>
    <script>
        function createLink() {
          var lat = document.getElementById("lat").value;
          var lng = document.getElementById("lng").value;
          var link = "https://maps.google.com/?q=" + lat + "," + lng;
        //   document.getElementById("locationLink").href = link;
        //   $('#id_location').val(link);
          document.getElementById("id_location").value = link;
        }
      </script> -->

</head>
<body>
    <h1>Create Order</h1>
    <form method="post" enctype="multipart/form-data" id="orderform" data-models-url="{% url 'ajax_load_models' %}">
      {% csrf_token %}
      <ul>
         <label for="">Vehicle</label><br>
         {{form.vehicle}}
         <br>
         <label for="">Type</label><br>
         {{form.type}}
         <br>
         <label for="">Model</label><br>
         {{form.model}}
         <br>
         <label for="">Defect</label><br>
         {{form.defect}}
         <br>
         <label for="">Description</label><br>
         {{form.description}}
         <br>
         <label for="">Phone Number</label><br>
         {{form.u_phone_number}}
         <br>
         <label for="">Latitude</label><br>
         {{form.latitude}}
         <br>
         <label for="">Longitude</label><br>
         {{form.longitude}}
         <br>
         <input type="date" name="myDate">
         <input type="time" name="myTime">


      </ul>
      <input type="file" name="images" multiple>
      <br>
      <br>
      <br>
      <input type="submit" value="Create Order">
    </form>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $("#id_vehicle").change(function(){
        const url = $("#orderform").attr("data-models-url");
        const vehicleId = $(this).val();
        console.log('url',url)

        $.ajax({
          url: url,
          data: {
            'vehicle_id': vehicleId
          },
          success: function (data) {
            $("#id_model").html(data);
          }
        })
      })
    </script>
    
</body>
</html>

templates/accounts/on_home_request.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">CREATE SERVICE REQUEST</h4>
                    <br>
                    <!-- <p class="text-center">Please fill this form to get yourself onboarded in the foodOnline marketplace.</p> -->
                    <hr>
                    <br>
                    <div id="restaurant-sets-holder">
                        <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" data-models-url="{% url 'ajax_load_models' %}" id="orderform" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >
                                                    <li>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Select Vehicle</label>{{form.vehicle}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Select Type</label>{{form.type}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Select Vehicle Model</label>{{form.model}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Select Defect</label>{{form.defect}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Description of the cause ( optional )</label>{{form.description}}
                                                            </div>
                                                        </div>
                                                       
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Images ( optional )</label>
                                                                <input type="file" name="images" multiple>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Contact Number</label>{{form.u_phone_number}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Date for Service</label>
                                                                <input type="date" name="myDate">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Time slot</label>
                                                                <input type="time" name="myTime">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Give current Latitude</label>{{form.latitude}}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Give current Longitude</label>{{form.longitude}}
                                                            </div>
                                                        </div>
                                                       
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                <ul style="text-align: center;" class="errorlist">
                                    {% for field in form %}
                                       {% if field.errors %}
                                        {% for error in  field.errors %}
                                           <li style="color: red;">{{error}}</li>
                                        {% endfor %}
                                       {% endif %}
                                    {% endfor %}
                                    <li style="color: red;">{{form.non_field_errors}}</li>
                                </ul>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div style="text-align: center;" class="payment-holder">
                                                    <input type="submit" value="Send Request" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                         {% include 'includes/alerts.html' %}
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $("#id_vehicle").change(function(){
    const url = $("#orderform").attr("data-models-url");
    const vehicleId = $(this).val();
    console.log('url',url)

    $.ajax({
      url: url,
      data: {
        'vehicle_id': vehicleId
      },
      success: function (data) {
        $("#id_model").html(data);
      }
    })
  })
</script>
{% endblock %}

templates/accounts/order_accept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous"
  />
</head>
<body>
    <form action="{% url 'accept' order.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="phone_number">Phone Number</label>
          <input type="text" class="form-control" id="phone_number" name="phone_number" required>
        </div>
        {% if not order.date %}
        <div class="form-group">
          <label for="eta">Estimated Time of Arrival</label>
          <input type="text" class="form-control" id="eta" name="eta" required>
        </div>
        {% endif %}
        <div class="form-group text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
</body>
</html>

templates/accounts/search.html
search page

templates/accounts/vendorHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <h1>vendor Home</h1>
<button><a href="{% url 'vendor_dashboard' %}">Dashboard</a></button>
<button><a href="{% url 'logout' %}">Logout</a></button>
<button><a href="{% url 'order_bill' %}">Bills</a></button>
<br>
<br>
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Created Date</th>
        <th>Service</th>
        <th>Model</th>
        <th>Defect</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
        <td>{{ order.created_at }}</td>
        <td>{{ order.service }}</td>
        <td>{{ order.model.name }}</td>
        <td>{{ order.defect.name }}</td>
        <td><a href="{% url 'order_detail' order.id %}" class="btn btn-info">View</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- <script>
      setInterval(function() {
        location.reload();
      }, 5000); // Refresh the page every 5 seconds
    </script> -->
</body>
</html>