accounts/urls.py
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.myAccount),
    path('registerUser/',views.registerUser, name='registerUser'),
    path('registerVendor/',views.registerVendor, name='registerVendor'),
    
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),

    path('activate/<uidb64>/<token>/',views.activate, name='activate'),

    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/',views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/',views.reset_password, name='reset_password'),

    path('myAccount/',views.myAccount, name='myAccount'),
    path('userHome/',views.userHome, name='userHome'),
    path('vendorHome/',views.vendorHome, name='vendorHome'),

    path('vendor_dashboard/',views.vendor_dashboard, name='vendor_dashboard'),
    path('v_orders/',views.v_orders, name='v_orders'),
    path('v_orders_detail/<int:order_id>',views.v_orders_detail, name='v_orders_detail'),

    path('user_dashboard/',views.user_dashboard, name='user_dashboard'),
    path('my_orders/',views.my_orders, name='u_my_orders'),
    path('my_orders_detail/<int:order_id>',views.my_orders_detail, name='u_my_orders_detail'),

    path('on_road/',views.on_road, name='on_road'),

    path('search/',views.search, name='search'),

    path('service/<int:vendor_id>/',views.service, name='service'),
    
    path('order/<int:vendor_id>/',views.order, name='order'),
    path('home_service/<int:vendor_id>/',views.home_service, name='home_service'),
    
    path('ajax/load-models/',views.load_models, name='ajax_load_models'),

    path('order_detail/<int:order_id>/',views.order_detail, name='order_detail'),
    path('order_bill/<int:order_id>/',views.order_bill, name='order_bill'),
    path('order_bill/',views.order_bill, name='order_bill'),

    path('user_bill/',views.user_bill, name='user_bill'),

    path('accept/<int:order_id>/',views.accept, name='accept'),
    path('decline/<int:order_id>/',views.decline, name='decline'),

    path('end_page/<uidb64>/<order_id>/',views.end_page, name='end_page'),


    path('vendor/',include('vendor.urls')),


   

    path('u_profile/',views.u_profile, name='u_profile'),

    path('admin_login/',views.admin_login, name='admin_login'),
    path('admin_logout/',views.admin_logout, name='admin_logout'),
    path('admin_home/',views.admin_dashboard, name='admin_dashboard'),
    path('admin_orders/',views.admin_orders, name='admin_orders'),
    path('admin_orders_detail/<int:order_id>',views.admin_orders_detail, name='admin_orders_detail'),

    path('admin_vendors/',views.admin_vendors, name='admin_vendors'),
    path('admin_users/',views.admin_users, name='admin_users'),

    path('admin_bill/',views.admin_bill, name='admin_bill'),
    path('user_block/<int:id>/',views.user_block, name='user_block'),
    path('user_unblock/<int:id>/',views.user_unblock, name='user_unblock'),
    path('vendor_block/<int:id>/',views.vendor_block, name='vendor_block'),
    path('vendor_unblock/<int:id>/',views.vendor_unblock, name='vendor_unblock'),


]

ajio_main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from accounts.models import User
from vendor.models import Vendor
from django.db.models import Count
# Create your models here.
class Defects(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
        
class Vehicle(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Models(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name 

 

class Types(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Orders(models.Model):
    TYPE = [
        ('ROAD', 'ROAD'),
        ('HOME', 'HOME'),
    ]
    STATUS_CHOICES = [
        ('NEW', 'NEW'),
        ('ACCEPTED', 'ACCEPTED'),
        ('DECLINED', 'DECLINED'),
        ('COMPLETED', 'COMPLETED'),
        ('PENDING', 'PENDING'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, blank=True, null=True)
    service = models.CharField(max_length=10, choices=TYPE, blank=True)
    u_phone_number = models.CharField(max_length=12, blank=True)
    v_phone_number = models.CharField(max_length=12, blank=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='NEW')
    type = models.ForeignKey(Types, on_delete=models.CASCADE, blank=True, null=True)
    model = models.ForeignKey(Models, on_delete=models.CASCADE, blank=True, null=True)
    defect = models.ForeignKey(Defects, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50, blank=True, null=True)
    eta = models.CharField(max_length=200, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    msg = models.TextField(blank=True, null=True)
    is_seen = models.BooleanField(default=False)
    date = models.DateField(blank=True,null=True)
    time = models.TimeField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.description

  

class Order_images(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='product_images')

    def __str__(self):
        return self.order.description       
   
                       

accounts/forms.py
from django import forms
from .models import User,UserProfile
from orders.models import Orders,Models

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Password doesn't match!")   

class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Start Typing...','required':'required'}))
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class':'btn btn-primary'}))
    cover_photos = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class':'btn btn-primary'}))
    latitude = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    longititude = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    class Meta:
        model = UserProfile     
        fields = ['profile_picture','cover_photos','address','country','state','city','pin_code','latitude','longititude',]       

class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ['vehicle','type', 'model', 'defect', 'description','u_phone_number','latitude','longitude']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = Models.objects.none()

        if 'vehicle' in self.data:
            try:
                vehicle_id = int(self.data.get('vehicle'))
                self.fields['model'].queryset = Models.objects.filter(vehicle_id=vehicle_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['model'].queryset = self.instance.vehicle.model_set.order_by('name')        

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number']            

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Account Setting</title>
        <!-- Google Font Family Link Start -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
        <!-- Google Font Family Link End -->
        <!-- Bootstrap Link Start-->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-datepicker.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
        <!-- <link href="{% static 'css/custom.css' %}" rel="stylesheet"> -->
        <!-- Bootstrap Link End-->
        <!-- Iconmoon Link Start-->
        <link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
        <!-- Iconmoon Link End-->
        <!-- Animate Link Start-->
        <link href="{% static 'css/animate.css' %}" rel="stylesheet">
        <!-- Animate Link End-->
        <!-- Chosen Link Start-->
        <link href="{% static 'css/chosen.css' %}" rel="stylesheet">
        <!-- Chosen Link End-->
        <!-- Swiper Link Start-->
        <link href="{% static 'css/swiper.css' %}" rel="stylesheet">
        <!-- Swiper Link End-->
        <!-- Woocommerce Link Start-->
        <link href="{% static 'css/woocommerce.css' %}" rel="stylesheet">
        <!-- Woocommerce Link End-->
        <!-- Pretty Photo Link Start-->
        <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
        <!-- Pretty Photo Link End-->
        <!-- Daterange Picker Link Start-->
        <link href="{% static 'css/daterangepicker.css' %}" rel="stylesheet">
        <!-- Daterange Picker Link End-->
        <!-- Pretty Photo Link Start-->
        <link href="{% static 'css/jquery.mCustomScrollbar.css' %}" rel="stylesheet">
        <!-- Pretty Photo Link End-->
        <!-- Themes / plugin Link Start-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
        <link href="{% static 'css/color.css' %}" rel="stylesheet">
        <link href="{% static 'css/widget.css' %}" rel="stylesheet">
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
        <!-- <link href="assets/css/rtl.css" rel="stylesheet"> -->
        <!-- Themes / plugin Link End-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="{% static 'js/modernizr.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        
        {% if 'userHome' in request.path or 'profile' in request.path or 'u_profile' in request.path %}
        <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
        {% endif %}

        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      
        
        <!-- <script src="{% static 'js/custom.js' %}"></script> -->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
    
    </head>
    <style>
.box {
  background-color: white;
  border-radius: 25px;
  border: 2px solid black;
  padding: 20px;
  text-align: center;
  margin-bottom: 20px;
  box-sizing: border-box;
  height: 150px;
  /* width: 100%; */
}

/* @media (min-width: 375px) { */
  /* .box { */
    /* width: 120%; */
    /* margin-right: 15px; */
    /* margin-left: 15px; */
  /* } */
/* } */
    </style>
<body>
  <div style="width: 100%; margin: auto; margin-top: 50px;">
  <h1 style="text-align: center;">AJIO ONLINE SERVICE</h1>
  <br>
  </div>

     

    {% block content%}

    {% endblock %}


   
    
    <script src="{% static 'js/responsive.menu.js' %}"></script>
	<script src="{% static 'js/swiper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/chosen.js' %}"></script>
	<script src="{% static 'js/counter.js' %}"></script>
	<script src="{% static 'js/fliters.js' %}"></script>
	<script src="{% static 'js/jquery.fitvids.js' %}"></script>
	<script src="{% static 'js/jquery.growl.js' %}"></script>
	<script src="{% static 'js/jquery.matchHeight-min.js' %}"></script>
	<script src="{% static 'js/masonry.pkgd.js' %}"></script>
	<script src="{% static 'js/skills-progress.js' %}"></script>
	<script src="{% static 'js/bootstrap-slider.js' %}"></script>
	<script src="{% static 'js/wow.js' %}"></script>
	<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
	<script src="{% static 'js/daterangepicker.js' %}"></script>
	<script src="{% static 'js/functions-plugin.js' %}"></script>
	<script src="{% static 'js/functions.js' %}"></script>
</body>
</html>

templates/end_page.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}


    
{% if order.status == 'COMPLETED' %}
    <!-- Completed -->
    <div style=" padding:10px; width:90%; min-height: 600px; background-color:white; margin: auto; display: flex; justify-content:center; margin-top: 50px;  ">
        <div style="margin: auto; display: flex; flex-direction: column;">
            <h1>This Service request has already Completed !</h1>
            <a style=" text-align: center; margin-bottom: 10px;" href="{% url 'myAccount' %}"><button style="margin-top: 50px;" class="btn btn-danger btn-lg">Go Home</button></a>
        </div>
        </div>
{% else %}
    {% if order.v_phone_number %}
     <!-- success -->
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; justify-content:center; margin-top: 50px;  ">
        <img style="margin-top: 50px; margin-bottom: 50px;" src="{% static 'images/success.png' %}" alt="">
        </div>
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; flex-direction: column;">
        <h1 style=" color:green; text-align: center;">SUCCESS !</h1>
        <br>
        {% if order.service == 'HOME' %}
        <h2 style="text-align: center;">Your Service will be provided on {{ order.date }}.</h2>
        <br>
        {% else %}
        <h2 style="text-align: center;">Your Service is On the way...</h2>
        {% endif %}
        </div>
        {% if order.service == 'ROAD' %}
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; justify-content:center;">
            <div style="width:100%; margin:auto; display: flex; justify-content:center;">
                <img style="width: 250px;" src="{% static 'images/ally1.jpg' %}" alt="">
            </div>
        {% endif %}    
            
        </div>
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; flex-direction: column;">
            <h2 style="text-align: center;">Keep in contact with your ally:</h2>
            <br>
            <h3 style="text-align: center;">{{order.v_phone_number}}</h3>
            {% if not order.date %}
            <br>
            <h2 style="text-align: center;">Estimated time of arrival : {{order.eta}}</h2>
            {% endif %}
            <a style="text-align: center; margin-bottom: 10px;" href="{% url 'myAccount' %}"><button style="margin-top: 50px;" class="btn btn-danger btn-lg">Go Home</button></a>
            </div>

    {% elif order.msg %}
    <!-- declined -->   
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; justify-content:center; margin-top: 50px;  ">
        <img style=" width: 150px; margin-top: 50px;" src="{% static 'images/declined.jpg' %}" alt="">
        </div>
        <div style="width:90%; min-height: auto; background-color:white; margin: auto; display: flex; flex-direction: column;">
        <h1 style=" color:green; text-align: center;">SORRY !</h1>
        <br>
        <h2 style="text-align: center;">Your Service has been Declined !</h2>
        </div>

        <div style="width:90%; min-height: 300px; background-color:white; margin: auto; display: flex; flex-direction: column;">
            <br>
            <h2 style="text-align: center;">The requested Ally declined your request</h2>
            <br>
            <h3 style="text-align: center;"><b>"{{order.msg}}"</b></h3>
            <br>
            <a style="text-align: center; margin-bottom: 10px;" href="{% url 'myAccount' %}"><button style="margin-top: 50px;" class="btn btn-danger btn-lg">Go Home</button></a>
            </div>
    {% endif %}    
{% endif %}    




{% endblock %}

templates/home.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
	<!-- Main Section Start -->
	{% for order in orders %}
	{% if order.status == 'ACCEPTED' %}
	<div class="alert alert-success show-notification" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Your service request on {{order.created_at}} is Accepted. Check your Mail for more details.</strong>
    </div>
	{% elif order.status == 'DECLINED' %}
	<div class="alert alert-danger show-notification" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Your service request on {{order.created_at}} is Declined. Check your Mail for more details.</strong>
    </div>
	{% endif %}
	{% endfor %}  

	{% include 'includes/alerts.html' %}
	<div class="main-section">
		<!-- Home Pages Elements Strat -->
		<!-- Main Search Start -->
		<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url(https://images.pexels.com/photos/56832/road-asphalt-space-sky-56832.jpeg?cs=srgb&dl=pexels-pixabay-56832.jpg&fm=jpg) no-repeat center / cover;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div class="element-title">
							<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
								We are here to help you out<br>With most popular workshops</h1>
							<p style="font-size: 28px; letter-spacing: 1px; color: black !important; text-align:center; margin-bottom: 15px;">
								<b>Find your ally</b></p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
						<div style="border-radius: 20px; background-color: darkblue !important;" class="main-search fancy bg-holder">
							<form action="{% url 'search' %}" method="GET">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-5 col-xs-12">
										<div class="field-holder">
											<input id="workshop-name" style="width: 100%;" type="text" placeholder=" Enter Workshop name" name="keyword">
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
										<div class="field-holder">
											<ul>
												<li class="select-location">
													<div class="foodbakery-locations-fields-group foodbakery-focus-out">
														<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
														<span id="foodbakery_radius_location_open333" class="foodbakery-radius-location"></span>
														<input style="width:100%; " type="text" class="location-field-text filter" placeholder="Enter the Location" name="address" id="id_address">
														<input type="hidden" name="lat" value="" id="id_latitude">
														<input type="hidden" name="lng" value="" id="id_longititude">
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
										<div class="field-holder">
											<button style="width:100%" type="submit"><input style="background-color: red;" type="submit" value="Search"></button>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<!-- Main Search End -->
		
		<!-- Top Restarurants Section Start -->
		<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="element-title" style="text-align: center;">
							<h2>Popular Workshops</h2>
							<p>Explore the services from the top most workshops</p>
						</div>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="company-logo" >
							<ul style="text-align: center; margin-top: 20px;">
								{% for vendor in vendors %}
								<li class="has-border">
									<figure>
										{% if vendor.user_profile.profile_picture %}
										<a href="{% url 'on_road' %}"><img src="{{ vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt=""></a>
										{% else %}
										<a href="{% url 'on_road' %}"><img src="{% static 'images/vendor icon.jpg' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										{% endif %}
									</figure>
								</li>
                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Restarurants Section End -->
		<!-- Choose From Most Popular Listin Start -->
		<div class="container-fluid bg-white">
             <img style="margin-top: 25px; margin-bottom: 25px;" src="{% static 'images/page.png' %}" alt="">
		</div>
	</div>
	<!-- <script>
		var div = document.getElementById('workshop-name');
		var value = div.innerHTML;
		console.log(value)
		setInterval(function() {
			location.reload();
		}, 5000); // Refresh the page every 5 seconds
	  </script> -->
	<!-- Main Section End -->
{% endblock %}

templates/request_accept.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div style="min-height: 600px; background-color: rgb(217, 221, 237); width: 100%; display: flex; justify-content: center; align-items:center ;">
    <form action="{% url 'accept' order.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="phone_number">Phone Number</label>
          <input style="width: 400px;" type="text" class="form-control" id="phone_number" name="phone_number" required>
        </div>
        {% if not order.date %}
        <div class="form-group">
          <label for="eta">Estimated Time of Arrival</label>
          <input type="text" class="form-control" id="eta" name="eta" required>
        </div>
        {% endif %}
        <div class="field-holder">
            <div style="text-align: center;" class="payment-holder">
                <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
            </div>
        </div>
      </form>
</div>

{% endblock %}

templates/request_decline.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div style="min-height: 600px; background-color: rgb(217, 221, 237); width: 100%; display: flex; justify-content: center; align-items:center ;">
    <form action="{% url 'accept' order.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="phone_number">Reason for Decline the request</label>
          <textarea style="width: 400px;" type="text" class="form-control" id="phone_number" name="phone_number" required rows="5"></textarea>
        </div>
        <div class="field-holder">
            <div style="text-align: center;" class="payment-holder">
                <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
            </div>
        </div>
      </form>
</div>

{% endblock %}

templates/request_detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
    <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}"></script>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <div style=" padding: 20px; width:95%; min-height: auto; background-color:rgba(200, 198, 217, 0.83); margin: auto; display: flex; flex-direction: column; margin-top: 70px;">
        <br>
        <h1 style="text-align: center;">Service Request Details</h1>
        <br>
        <h4 style="text-align: center;">Service : <b>{{order.service}}</b></h4>
        <h4 style="text-align: center;">Vehicle : <b>{{order.vehicle}}</b></h4>
        <h4 style="text-align: center;">Type : <b>{{order.type}}</b></h4>
        <h4 style="text-align: center;">Model : <b>{{order.model}}</b></h4>
        <h4 style="text-align: center;">Defect : <b>{{order.defect}}</b></h4>
        <h4 style="text-align: center;">Description : <b>{{order.description}}</b></h4>
        <h4 style="text-align: center;">Customer No : <b>{{order.u_phone_number}}</b></h4>
        {% if order.date %}
        <h4 style="text-align: center;">Date for Service: <b>{{order.date}} - {{order.time}}</b></h4>
        {% endif %}
        <h3 style="text-align: center; color: darkblue;">Location</h3>
        <br>
        <div id="map" style="width: 300px; height:300px; margin: auto;"></div>
        </div>
      <div class="row">
        <div class="col-lg-12" style="height: max-content; text-align: center; display: flex; justify-content: center; align-items: center; flex-wrap: wrap; gap: 20px;">
            {% for image in images %}
              <div class="card" style="width: 200px; height: 200px; margin: 15px;">
                <img style="width: 200px; height: 200px; object-fit:contain;" src="{{image.images.url}}" class="card-img-top" alt="">
              </div>
            {% endfor %}
          </div>
      </div>
    </div>
    <div class="row mt-5" style="margin-bottom: 20px;">
        <div class="col-md-12 text-center">
          <a href="{% url 'accept' order.id %}"><button class="btn btn-success">Accept</button></a>
          <a href="{% url 'decline' order.id %}"><button class="btn btn-danger">Decline</button></a>
        </div>
      </div>
      <script>
        function initMap(lat, lng) {
  var myLatLng = {lat: lat, lng: lng};

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 8,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map
  });
}
      </script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/
{% endblock %}